# Aetheris authorization policy (versioned, OPA v1 syntax).
#
# This is the source-of-truth policy consulted by OpaBridge via
# POST {OPA_ENDPOINT}/v1/data/aetheris/authz/allow. It is no longer generated by
# scripts/bootstrap.sh - commit changes here and reload with `opa eval` / the
# OPA bundle pipeline as appropriate.
#
# Input contract (see core/src/bridge.rs AuthzInput):
#   input.identity  string  Cloudflare Access identity
#   input.role      string  admin | analyst | unknown  (derived from identity)
#   input.method    string  HTTP method (GET, POST, ...)
#   input.path      string  request path
#   input.action    string  logical action (read, write, ...)
package aetheris.authz

default allow = false

allow if input.role == "admin"

allow if {
    input.role == "analyst"
    input.method == "GET"
}
