[Interface]
Address = 10.88.99.3
PrivateKey = 4MxrHVtcJ2X0Hazdlt79HtLN7NtrJkKwll67JrIH21Y=
ListenPort = 51820
DNS = 10.88.99.0

[Peer]
PublicKey = kX00EjqkVrBHR0FLVDYgrtkP4urdTG6eJS3hc3Ca3C4=
PresharedKey = HdFYTPSwGChOktuBDLzOALSXyX/XEhYkbbwd4Gov+SM=
PresharedKey = HdFYTPSwGChOktuBDLzOALSXyX/XEhYkbbwd4Gov+SM=
Endpoint = 0.0.0.0:51820
AllowedIPs = 0.0.0.0/0, ::/0
