[Interface]
Address = 10.88.99.2
PrivateKey = SD8XYP3LawnwkPi8MaLl6YMWs78/KatsAmZnUqWiCkA=
ListenPort = 51820
DNS = 10.88.99.0

[Peer]
PublicKey = kX00EjqkVrBHR0FLVDYgrtkP4urdTG6eJS3hc3Ca3C4=
PresharedKey = fJ3dNTOQ0yKeYOUj3PmkD8BkBb9A3mO331Y//Ayg+Vg=
PresharedKey = fJ3dNTOQ0yKeYOUj3PmkD8BkBb9A3mO331Y//Ayg+Vg=
Endpoint = 0.0.0.0:51820
AllowedIPs = 0.0.0.0/0, ::/0
